apiVersion: skaffold/v1
kind: Config
metadata:
  name: job-status-to-apps-adapter
deploy:
  kubectl:
    manifests:
    - k8s/job-status-to-apps-adapter.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: discoenv/job-status-to-apps-adapter
  local: {}
